database_in=file:/etc/aide/aide.db
database_out=file:/etc/aide/aide.db.new
database_new=file:/etc/aide/aide.db.new
log_level=notice

# Overlayfs directory inode numbers are unstable, so inode checks are omitted.
Checks = p+n+u+g+s+m+c+sha256

!/etc/aide
!/tmp
!/var/run
!/run
!/proc
!/sys
!/dev

/bin Checks
/sbin Checks
/etc Checks
/lib Checks
/usr Checks
/www Checks
/root Checks
